<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="0" total="5" passed="2" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[<b>Login screen is being displayed</b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>User has entered Username </b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>User has entered Password </b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>Page Title After login is Login-AMT</b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>AMT-Logo is displayed</b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>AMT-Logo is displayed</b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>AMT-Logo is displayed</b> <br />]]>
    </line>
    <line>
      <![CDATA[<br>----------Screenshot---------<br>]]>
    </line>
    <line>
      <![CDATA[<img src="D:\newWorkspaceStaging\AutomationStaging\target\surefire-reports\html\failure_screenshots\amt_Logo_display_Test_10_11_2022_12_41_59.png" height="800" width="1000">]]>
    </line>
  </reporter-output>
  <suite started-at="2022-11-10T12:40:51 IST" name="AMT Automation Aquisition Quotes" finished-at="2022-11-10T12:42:00 IST" duration-ms="68505">
    <groups>
    </groups>
    <test started-at="2022-11-10T12:40:51 IST" name="LoginTest" finished-at="2022-11-10T12:42:00 IST" duration-ms="68505">
      <class name="com.amt.test.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:40:51 IST" name="setup" finished-at="2022-11-10T12:41:03 IST" duration-ms="11631" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login_Test()[pri:1, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:03 IST" name="login_Test" finished-at="2022-11-10T12:41:08 IST" duration-ms="5197" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[<b>Login screen is being displayed</b> <br />]]>
            </line>
            <line>
              <![CDATA[<b>User has entered Username </b> <br />]]>
            </line>
            <line>
              <![CDATA[<b>User has entered Password </b> <br />]]>
            </line>
          </reporter-output>
        </test-method> <!-- login_Test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:08 IST" name="tearDown" finished-at="2022-11-10T12:41:09 IST" duration-ms="430" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:09 IST" name="setup" finished-at="2022-11-10T12:41:22 IST" duration-ms="13883" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="pageTitle_Test()[pri:2, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:22 IST" name="pageTitle_Test" finished-at="2022-11-10T12:41:22 IST" duration-ms="5" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[<b>Page Title After login is Login-AMT</b> <br />]]>
            </line>
          </reporter-output>
        </test-method> <!-- pageTitle_Test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:22 IST" name="tearDown" finished-at="2022-11-10T12:41:23 IST" duration-ms="372" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:23 IST" name="setup" finished-at="2022-11-10T12:41:32 IST" duration-ms="9185" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method retried="true" signature="amt_Logo_display_Test()[pri:3, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:32 IST" name="amt_Logo_display_Test" finished-at="2022-11-10T12:41:34 IST" duration-ms="2011" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at com.amt.test.LoginTest.amt_Logo_display_Test(LoginTest.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<b>AMT-Logo is displayed</b> <br />]]>
            </line>
          </reporter-output>
        </test-method> <!-- amt_Logo_display_Test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:34 IST" name="tearDown" finished-at="2022-11-10T12:41:34 IST" duration-ms="423" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:34 IST" name="setup" finished-at="2022-11-10T12:41:45 IST" duration-ms="10293" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method retried="true" signature="amt_Logo_display_Test()[pri:3, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:45 IST" name="amt_Logo_display_Test" finished-at="2022-11-10T12:41:48 IST" duration-ms="2923" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at com.amt.test.LoginTest.amt_Logo_display_Test(LoginTest.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<b>AMT-Logo is displayed</b> <br />]]>
            </line>
          </reporter-output>
        </test-method> <!-- amt_Logo_display_Test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:48 IST" name="tearDown" finished-at="2022-11-10T12:41:48 IST" duration-ms="344" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:48 IST" name="setup" finished-at="2022-11-10T12:41:57 IST" duration-ms="9087" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="amt_Logo_display_Test()[pri:3, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:57 IST" name="amt_Logo_display_Test" finished-at="2022-11-10T12:41:59 IST" duration-ms="2044" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at com.amt.test.LoginTest.amt_Logo_display_Test(LoginTest.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<b>AMT-Logo is displayed</b> <br />]]>
            </line>
            <line>
              <![CDATA[<br>----------Screenshot---------<br>]]>
            </line>
            <line>
              <![CDATA[<img src="D:\newWorkspaceStaging\AutomationStaging\target\surefire-reports\html\failure_screenshots\amt_Logo_display_Test_10_11_2022_12_41_59.png" height="800" width="1000">]]>
            </line>
          </reporter-output>
        </test-method> <!-- amt_Logo_display_Test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.amt.test.LoginTest@c88a337]" started-at="2022-11-10T12:41:59 IST" name="tearDown" finished-at="2022-11-10T12:42:00 IST" duration-ms="451" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.amt.test.LoginTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- AMT Automation Aquisition Quotes -->
</testng-results>
