<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DSK-4052" failures="1" tests="3" name="newCar.LoginTest" time="6.932" errors="0" timestamp="2023-06-02T15:55:39 IST" skipped="0">
  <testcase classname="newCar.LoginTest" name="login_Test" time="1.872"/>
  <system-out>
    <![CDATA[<b>Login screen is being displayed</b> <br />
<b>User has entered Username </b> <br />
<b>User has entered Password </b> <br />]]>
  </system-out>
  <testcase classname="newCar.LoginTest" name="pageTitle_Test" time="5.014">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at newCar.LoginTest.pageTitle_Test(LoginTest.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- pageTitle_Test -->
  <system-out>
    <![CDATA[<b>Page Title After login is AMT</b> <br />
<br>----------Screenshot---------<br>
<img src="D:\usedCar\AMT_Automation\target\surefire-reports\html\failure_screenshots\pageTitle_Test_02_06_2023_03_55_38.png" height="800" width="1000">
<br>----------Screenshot---------<br>
<img src="D:\usedCar\AMT_Automation\FailedTestsScreenshots\pageTitle_Test20230602035538.png" height="800" width="1000">]]>
  </system-out>
  <testcase classname="newCar.LoginTest" name="amt_Logo_display_Test" time="0.046"/>
  <system-out>
    <![CDATA[<b>AMT-Logo is displayed</b> <br />]]>
  </system-out>
</testsuite> <!-- newCar.LoginTest -->
